### ISSUE TITLE
Do we need local_child_span_count at all?

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-proto#105]
There were no feedback on what scenarios will be affected by https://github.com/open-telemetry/opentelemetry-proto/pull/90

Do we need this field in proto at all since it's not in the specs?

**Comment by SergeyKanzhelev** [comment]
@tigrannajaryan and @bogdandrutu suggests we remove it for now

**Comment by yurishkuro** [comment]
I thought the field was meant to help catching data loss. What changed?

NB: in Jaeger we recently introduced other fields for detecting data loss (https://github.com/jaegertracing/jaeger-idl/pull/60).

**Comment by SergeyKanzhelev** [comment]
Nobody commented on the PR to change the semantics of `0` of this field. And it's not in the specification. In general it's not straightforward how this number must be calculated. So we discussed and decided that perhaps we can remove it for now. Maybe reusing what you implemented in Jaeger is a good idea

**Comment by SergeyKanzhelev** [comment]
we want to remove it for beta so we have time to discuss and not to break the schema later

**Comment by tigrannajaryan** [comment]
@yurishkuro we are not certain what exactly this field should look like. We will most likely add it to the proto as soon as there is clarity. Adding a new field is typically backwards compatible in ProtoBuf, removing or changing semantics is not, so we want to play safe for now.

**Comment by gbbr** [comment]
I don't have strong feelings for keeping this field, but it does seem like it could be key in solving a key problem we've been investigating at Datadog. It runs similar along the lines mentioned by @yurishkuro around data integrity.

In short, at Datadog it is key to the product to have complete traces before processing them. This helps us offer some functionalities specific to our platform. Currently our clients aggregate spans into complete traces but this brings forward performance limitations and complexity so we are trying to move the "trace reconstruction" logic elsewhere. When this is done anywhere else other than the client, the question "is this trace complete?" becomes much harder to answer.

We have not yet started working on this final prototype, nor investigated enough, but one idea which seems to have helped solve this question of when a trace is complete would have been a field which counts the number of child spans started locally. If this turns out to be the right solution, as I suspect, we will likely be adding it into our data structures. Keeping it in OpenTelemetry will help us better integrate with this open standard.

**Comment by SergeyKanzhelev** [comment]
@gbbr absolutely. My worry is that if it will be in proto and no SDK will populate it as we don't have specs - we will have bunch of inconsistently behaving SDK versions at some point. Do you want to drive the specification part of it so we introduce it back with the clear definition how to use it?

The suggestion is to remove it in beta and introduce it back as soon as we have a clear understanding of this field semantics.

**Comment by gbbr** [comment]
> Do you want to drive the specification part of it so we introduce it back with the clear definition how to use it?

Sure! I'm happy to help define it. I've never contributed to anything in this org, so if you could guide me to what the best way of doing it is, that'd be appreciated. Should it be a PR on a file in one of the repositories? On the proto file? On a spec somewhere?

**Comment by SergeyKanzhelev** [comment]
I'd suggest to start with the [otep](https://github.com/open-telemetry/oteps/#opentelemetry-enhancement-proposal-otep) PR. Once the proposal is formally "accepted" as OTEP, spec needs to be written in [specification repo](https://github.com/open-telemetry/opentelemetry-specification/).
