### ISSUE TITLE
Clarify temporality (aggregation vs measurement)

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-proto#184]
From @jmacd:

I realize now the source of confusion for me w.r.t. Temporality is that it sometimes applies to the individual Metric (i.e., is this a change in a sum or a total sum?) and it sometimes applies to the collection strategy (i.e., am I returning all "active" Metrics since the beginning of the process or since the last report).

I think we should find a way to distinguish these two ideas with terminology. A practical way to probe this issue is that I might like to encode the following things:

1. A Histogram of deltas from the start of the process (dimensionally reduced or not)
1. A Histogram of cumulatives from the start of the process (probably dimensionally reduced otherwise just one value)
1. A Histogram of deltas from a recent interval (dimensionally reduced or not)
1. A Histogram of cumulatives at the end of a recent interval (probably dimensionally reduced otherwise just one value)
There's a question as to whether (2) and (4) are any different, probably they are not, but you can imagine different interpretations because in (2) you can't forget any timeseries, and in (4) you can omit timeseries that hvaen't been "active" in the latest window.

So, two ways to interpret Cumulative.

OTOH, I think we're having trouble distinguishing (1) and (2).

**Comment by jmacd** [comment]
I think we can close this issue, it only becomes relevant when considering raw values (#188).

**Comment by james-bebbington** [comment]
I think we said today that we are leaving raw values (from "exact" aggregations) out for now (will come back to this later) and also that we are only considering aggregation temporality rather than data temporality (unclear if the latter is needed yet).

Does that mean we should go ahead and remove `instantaneous` for the time being (and add that concept back in if needed when we have a clearer plan for how to express raw values), or does it still represent something meaningful outside of those two things?
