### ISSUE TITLE
Add labels to entry level tasks for new contributors

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry-proto#220]
Hi,

based on https://github.com/open-telemetry/community/issues/469 I have added **open-telemetry/opentelemetry-proto** to Up For Grabs:

https://up-for-grabs.net/#/filters?names=660

There are currently no issues with label [help wanted](https://github.com/open-telemetry/opentelemetry-proto/labels/help%20wanted). Please add this label to your entry level tasks, so people can find a way to contribute easily. 

If "help wanted" is not the right label, let me know and I can change it (e.g. to "good first issue" or "up-for-grabs"), or you can provide a pull request by editing https://github.com/up-for-grabs/up-for-grabs.net/blob/gh-pages/_data/projects/opentelemetry-proto.yml

Thanks!

**Comment by bogdandrutu** [comment]
Hi @svrnm, and thank you for showing interest to work on this. For the moment we do not offer this, because proto is a small repository and for the moment we do not have too many items available to grab. Probably we should remove this repo from up-for-grabs, and when we get this repo more stable/mature we should start doing that

**Comment by tigrannajaryan** [comment]
We are now adding "help wanted" labels where relevant. Closing.
