### ISSUE TITLE
Host a centralized build of the OTLP 

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-proto#238]
From https://github.com/open-telemetry/opentelemetry-go/issues/1324

> For reasons that are (probably still) sensible, the `go.opentelemetry.io/exporters/otlp/internal/opentelemetry-proto-gen` is an internal package and I'm not able to depend on it for my own applications. Now suppose I've written an application that handles OTLP data itself but is also instrumented by an OTel-Go SDK. I need a copy of the OTLP protocol for my own application, but the Google and Gogo protocol buffer implementations emit warnings when you register the same protocol message name twice. 
> 
> Simply put, if I generate my own copy of these protocol messages and link them with an OTel-Go SDK, I get a conflict. How should this be handled, in general? It seems to require the use of `sed` to change protocol package names, which leaves me in a complicated an unhappy position. As it stands, I do have such an application and I've manually done this once, but it was painful and it will happen the more people try to build custom OTLP pipelines.

To resolve this issue it would be ideal to unify the OTLP generated code dependency so both the opentelemetry-go and downstream users can depend on the same code and avoid this type of problem. A prior issue (#79) removed this type of a solution because it was seen as a "hidden implementation detail". Given we have real users asking for this use case it seems like the alternative solutions discussed in that issue need to be explored: hosting the code in this repository, or in a separate dedicated repository.

**Comment by jkwatson** [comment]
java users are having the same request. I wonder if we should have a separate repo that is just responsible for building and publishing the protobuf bindings for all relevant languages.

/cc @anuraaga

**Comment by anuraaga** [comment]
@MrAlias I raised this just recently but saw very little appetite for it and didn't pursue. If more people ask for it maybe we can do it though.

https://github.com/open-telemetry/opentelemetry-proto/pull/231

I do think it's a good idea - and while there could be a separate repo, I'm not sure if there's a good reason to. This repo has the version tags, so using them when publishing seems intuitive.

**Comment by MrAlias** [comment]
I'm open to either solution of hosting in this repository or a dedicated one. It sounded like @tigrannajaryan was a bit hesitant to create a new repository, and you make a good point @anuraaga that this repository already has the version tags so it seems like the logical place.

**Comment by gcacace** [comment]
It would be nice to have a dedicated bindings package for every supported language (e.g.: `opentelemetry-proto-java`, `opentelemetry-proto-python`) and SDKs can depend on those instead of building their own bindings in many different ways. This would make smoother tre release process which at the moment seems to be quite convoluted. Here below an example of how the Java bindings release process looks like now:
* New proto version released (with its own versioning)
* Java SDK community has to manually bump-up the consumed proto version and run creation of bindings
* Java SDK is currently responsible of pushing the proto bindings in Maven Central (with Java SDK versioning)

How the process would look like in case we have a per-language binding package:
* New proto version released (with its own versioning)
* Ideally the release of Java bindings could be fully automated (ensuring that the latest changes in the proto don't break the binding compiler) (with its own versioning which can follow the proto one [unless there are some changes in the binding configuration])
* Every consumer of the binding (such as Java OT SDK, other third party consumers) would find the new released proto instantly in Maven Central

**Comment by seanschade** [comment]
A dedicated package per supported language would be nice, and it could use the same semantic version from this repository.

Keeping the Protobuf definition separate from the generated code has a couple of benefits. We do this with our own Protobufs at Care and it works well.

1. Downstream builds can be triggered by releases to this repository.
2. Language specific build options are kept in their respective repositories keeping this repository small.

**Comment by anuraaga** [comment]
@yurishkuro Any thoughts on this? Seems like many people are interested in independent packages for the proto :)

**Comment by yurishkuro** [comment]
I have made my view known multiple times, in #79 and other issues. I do not maintain this `opentelemetry-proto` repo myself, so this is ultimately up to the active maintainers. But I would not want to maintain a **monorepo** that needs to understand and support:
  * N different languages,
    * as well as potentially different code generators, e.g. gogoproto has ~5 different variants
  * M different build systems (likely M=N),
  * K different CI systems (likely K >= 2),
  * and R different artifact repositories (likely R ~ N). 

Sounds like a nightmare, frankly.

The "shared versioning" argument does not convince me. First, independent repos can trigger builds from new releases in this repo, this does not require a monorepo approach. Second, I am very skeptical about keeping versioning in sync across different platforms. I am certain there will be situation where a single language needs to release a new version of the artifact because of new `protoc` or plugin version or something like that, not because there is a new release of the proto files themselves.

I am not against "many people ... interested in independent packages" doing the work to maintain those packages **in independent repos** - it is well scoped, and puts the burden on the right people with appropriate knowledge/skills.

**Comment by MrAlias** [comment]
> I am not against "many people ... interested in independent packages" doing the work to maintain those packages **in independent repos** - it is well scoped, and puts the burden on the right people with appropriate knowledge/skills.

I'm happy to pickup the Go side of things.

**Comment by gcacace** [comment]
I'm happy to help with the java one!

**Comment by tigrannajaryan** [comment]
I fully support what @yurishkuro said above, well articulated reasons why hosting the generated code here is undesirable. 

I think the choice is narrowed down to either hosting the generated code in each of already existing language specific repos where SDKs reside (e.g. opentelemetry-java) or have a separate repo per language just for the generated code (e.g. opentelemetry-java-otlp). 

Potentially, the separate repo may also contain a canonical full implementation of the OTLP protocol, a receiver and an exporter in the particular language, not just the Protobuf's generated code. The SDKs can then either import the full exporter implementation or just the generated code as they wish.

I think the choice of the location (separate repo or in the SDK) and if a separate repo is chosen the decision to have a full canonical implementation should be left to each language SDK maintainers.

If we are OK with the above then I invite each team of language maintainers to make a request for a separate repo if they wish so (submit an issue to request a new repo to https://github.com/open-telemetry/community) and we can close this issue.

**Comment by carlosalberto** [comment]
> I am not against "many people ... interested in independent packages" doing the work to maintain those packages in independent repos

"repos", not "repo", so I guess the suggestion is NOT to have a separated **single** repo to publish all those different language packages :)

**Comment by tigrannajaryan** [comment]
> "repos", not "repo", so I guess the suggestion is NOT to have a separated **single** repo to publish all those different language packages :)

Correct. Each language's code goes into its own repo, either a completely separate repo or the same repo where that language's Otel SDK currently lives in.

**Comment by MrAlias** [comment]
> either a completely separate repo or the same repo where that language's Otel SDK currently lives in.

I would like to avoid generating this project's code in the OTel SDK repositories. It would be inappropriate to not include the generated code from this repository here but ask other repositories that focus on other tasks and depend on this code to host the generated code there.

It sounds like the ideal solution is to host it in a separate repositories.

@tigrannajaryan is this something that needs to be discussed with the entire @open-telemetry/technical-committee or can we start creating these repositories?

**Comment by yurishkuro** [comment]
@MrAlias there are no additional TC discussions needed, individual Language SIGs can decide if they want to host gen-code in the SDK repos or new standalone repos.

**Comment by MrAlias** [comment]
> @MrAlias there are no additional TC discussions needed, individual Language SIGs can decide if they want to host gen-code in the SDK repos or new standalone repos.

Cool, good to know. Can we create a repository for the Go generated code?

I'm not sure how we wanted to standardize on the naming for these repositories. Would `opentelemetry-proto-go` work?

**Comment by yurishkuro** [comment]
https://github.com/open-telemetry/opentelemetry-proto-go

**Comment by tigrannajaryan** [comment]
I think we can close this issue. Any new repo requests can be filed at https://github.com/open-telemetry/community/issues as usual.

**Comment by sirianni** [comment]
Thanks @MrAlias and @jkwatson for pushing this forward!  Despite all the commentary in #79 it's pretty apparent that such a change is welcome.  The opentelemetry-go and opentelemetry-collector projects both generate the golang code in very different ways and both need to resort to `sed` trickery to work around package naming.  

For others reading this issue, here's the pattern that I've come up with to generate the protos in my downstream repo without needing to unhappily mess around with `sed` to hack package names.  _Disclaimer: I'm fairly new at go, so I'm not sure if there's any pitfalls here..._

1. Create a directory in my repo root called `opentelemetry-proto`
2. Add `https://github.com/open-telemetry/opentelemetry-proto` as a git submodule called `src` in that directory
3. Run `protoc` in that dir with the `--go_opt=module=github.com/open-telemetry/opentelemetry-proto` option to strip the package prefix
```
	find -name *.proto -exec protoc \
		-I=./src \
		-I=/opt/include \
		--go_out=.	 \
		--go_opt=module=github.com/open-telemetry/opentelemetry-proto \
```
4. Create a `go.mod` file in that directory with the following contents
```
module github.com/open-telemetry/opentelemetry-proto

go 1.15

require google.golang.org/protobuf v1.25.0
```
5. Use a `replace` directive in my project root's `go.mod` to point at that local directory.
```
require (
	github.com/open-telemetry/opentelemetry-proto v0.0.0-00010101000000-000000000000
)

replace github.com/open-telemetry/opentelemetry-proto => ./opentelemetry-proto
```
