### ISSUE TITLE
Missing `dropped_attributes_count` for *DataPoint in metrics

### ISSUE THREAD

**Issue by cwildman** [open-telemetry/opentelemetry-proto#326]
None of the DataPoint types (NumberDataPoint, HistogramDataPoint, SummaryDataPoint) include a `dropped_attributes_count` despite having an `attributes` field. This is inconsistent with every where else that `attributes` are in the data model which makes me think this is a bug.

**Comment by jsuereth** [comment]
Currently we don't allow metrics to drop attributes (or at least it's highly unspecified).  This is because dropping attributes leads to metric-identity change (and possibly very bad behavior) whereas it's acceptible for traces (as attributes are descriptive, not identifying).

We had an open issue for this a while back.

**Comment by tigrannajaryan** [comment]
Closing the issue since we can't drop metric attributes.
