### ISSUE TITLE
#![feature]` may not be used on the stable release channel

### ISSUE THREAD

**Issue by lcmgh** [open-telemetry/opentelemetry-proto#448]
When trying to generate docs with `cargo doc` for my app I am facing this error after adding opentelemetry crates:

```rust
 Documenting opentelemetry-proto v0.1.0
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /Users/x/.cargo/registry/src/github.com-1ecc6299db9ec823/opentelemetry-proto-0.1.0/src/lib.rs:1:18
  |
1 | #![cfg_attr(doc, feature(doc_auto_cfg))]
```

**Comment by flokli** [comment]
It looks like this is due to the usage of [`doc_auto_cfg`](https://doc.rust-lang.org/beta/unstable-book/language-features/doc-auto-cfg.html#doc_auto_cfg).

https://github.com/open-telemetry/opentelemetry-rust/issues/924 might be the correct place for it (where the rust code seems to live in), it says it should not be an issue without the `docsrs` feature.

**Comment by tigrannajaryan** [comment]
Closing since https://github.com/open-telemetry/opentelemetry-rust/issues/924 is resolved.
